# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: Hardware
# startup_pane: 0

windows:
  - Simulation: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom_ur_sim spawn_ur5_camera_gripper_moveit_table_yolo.launch.py
  - Yolo: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; source ~/yolo_env/env/bin/activate; sleep 3; ros2 launch yolov8_obb yolov8_obb.launch.py
  - Ui: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 4; python3 ~/devel_ws/src/moveit_2025/ui/bolt_selector.py
  - Hand_Gesture: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom_ur_sim test.launch.py
